PROGRAM JKZ
  USE BINIO
  USE BLAS_UTILS
  USE JSTEP
  USE OMP_LIB
  IMPLICIT NONE

  CHARACTER(LEN=FNL,KIND=c_char) :: FN
  INTEGER :: N, N_2, ID_MAG, ID_CMP, ID_CVG, ID_TRU, INFO, NN, NT, SZ(3), FD(3)
  TYPE(APROC) :: R

  COMPLEX(KIND=DWP), ALLOCATABLE, TARGET :: ZARR(:,:)
  COMPLEX(KIND=DWP), POINTER, CONTIGUOUS :: A(:,:), U(:,:), Z(:,:)
  REAL(KIND=DWP), ALLOCATABLE, TARGET :: DARR(:)
  REAL(KIND=DWP), POINTER, CONTIGUOUS :: S(:)
  INTEGER, ALLOCATABLE, TARGET :: IARR(:)
  INTEGER, POINTER, CONTIGUOUS :: J(:), P(:), Q(:), STEP(:)
  TYPE(DZBW), ALLOCATABLE, TARGET :: DZ(:)

  IF (.NOT. VERIFY_MIN_MAX()) STOP 'MIN and/or MAX do NOT handle NaNs properly!'
  CALL READCL(FN, N, N_2, ID_MAG, ID_CMP, ID_CVG, ID_TRU, INFO)
  IF (INFO .NE. 0) STOP 'jkz.exe FN N N_2 [ID_MAG [ID_CMP [ID_CVG [ID_TRU]]]]'
#ifndef NDEBUG
  WRITE (ULOG,'(A,A)')   '    FN=', TRIM(FN)
  WRITE (ULOG,'(A,I11)') '     N=', N
#endif
  IF (N .LE. 1) STOP 'N < 2'

  INFO = JSTEP_LEN(N, N_2)
  N_2 = INFO
#ifndef NDEBUG
  WRITE (ULOG,'(A,I11)') '   N_2=', N_2
#endif
  IF (INFO .LE. 0) STOP 'JSTEP_LEN'

  CALL APROC_INIT(ID_MAG, ID_CMP, ID_CVG, ID_TRU, R, INFO)
#ifndef NDEBUG
  WRITE (ULOG,'(A,I11)') 'ID_MAG=', ID_MAG
  WRITE (ULOG,'(A,I11)') 'ID_CMP=', ID_CMP
  WRITE (ULOG,'(A,I11)') 'ID_CVG=', ID_CVG
  WRITE (ULOG,'(A,I11)') 'ID_TRU=', ID_TRU
#endif
  IF (INFO .NE. 0) STOP 'APROC_INIT'

  CALL BOPEN_YJ_RO(FN, N, N, SZ, FD, INFO)
  IF (INFO .NE. 0) THEN
     WRITE (ULOG,'(A,I11)') 'INFO=', INFO
     STOP 'BOPEN_YJ_RO'
  END IF

  ALLOCATE(ZARR(N, 3 * N))
#ifndef NDEBUG
  !DIR$ VECTOR ALWAYS
  ZARR = Z_ZERO
#endif
  A => ZARR(:,1:N)
  U => ZARR(:,N+1:2*N)
  Z => ZARR(:,2*N+1:3*N)

  ALLOCATE(DARR(N))
#ifndef NDEBUG
  !DIR$ VECTOR ALWAYS
  DARR = D_ZERO
#endif
  S => DARR(1:N)

  ALLOCATE(IARR(N * N + N_2))
#ifndef NDEBUG
  !DIR$ VECTOR ALWAYS
  IARR = 0
#endif
  NN = (N * (N - 1)) / 2
  J => IARR(1:N)
  P => IARR(N+1:NN+N)
  Q => IARR(NN+N+1:2*NN+N)
  STEP => IARR(2*NN+N+1:2*NN+N+N_2)

  ALLOCATE(DZ(NN))
#ifndef NDEBUG
  !DIR$ VECTOR ALWAYS
  DO INFO = 1, NN
     DZ(INFO)%W = D_ZERO
     DZ(INFO)%P = 0
     DZ(INFO)%Q = 0
     DZ(INFO)%B = 0
  END DO
#endif

  CALL BREAD_YJ(FD, A, J, N, N, SZ, INFO)
  IF (INFO .NE. 0) THEN
     WRITE (ULOG,'(A,I11)') 'INFO=', INFO
     STOP 'BREAD_YJ'
  END IF
  CALL BCLOSEN(FD, 3)

  CALL R%TRU(N, P, Q, NN, INFO)
  IF (INFO .NE. NN) THEN
     WRITE (ULOG,'(A,I11)') 'INFO=', INFO
     STOP 'R%TRU'
  END IF
#ifndef NDEBUG
  WRITE (ULOG,'(A,I11)') '    NN=', NN
#endif

  INFO = BLAS_PREPARE()
  ! number of threads
  NT = MIN(MAX(1, INT(OMP_GET_MAX_THREADS())), N_2)
#ifndef NDEBUG
  WRITE (ULOG,'(A,I11)') '    NT=', NT
#endif

  IF (ALLOCATED(DZ)) DEALLOCATE(DZ)
  STEP => NULL()
  Q => NULL()
  P => NULL()
  J => NULL()
  IF (ALLOCATED(IARR)) DEALLOCATE(IARR)

  ! CALL BOPEN_UZS_RW(FN, N, N, SZ, FD, INFO)
  ! IF (INFO .NE. 0) THEN
  !    WRITE (ULOG,'(A,I11)') 'INFO=', INFO
  !    STOP 'BOPEN_UZS_RW'
  ! END IF

  ! CALL BWRITE_UZS(FD, U, Z, S, N, N, INFO)
  ! IF (INFO .NE. 0) THEN
  !    WRITE (ULOG,'(A,I11)') 'INFO=', INFO
  !    STOP 'BWRITE_UZS'
  ! END IF

  ! CALL BCLOSEN(FD, 3)

  S => NULL()
  IF (ALLOCATED(DARR)) DEALLOCATE(DARR)
  Z => NULL()
  U => NULL()
  A => NULL()
  IF (ALLOCATED(ZARR)) DEALLOCATE(ZARR)

  STOP 'jkz.exe successfully terminated'
CONTAINS
#include "readcl.F90"
#include "bio.F90"
END PROGRAM JKZ
