PROGRAM ZTEST
  USE ZTRANSF
  IMPLICIT NONE

  COMPLEX(KIND=DWP) :: A(2,2), U(2,2), Z(2,2), B(2,2)
  COMPLEX(KIND=16) :: C(2,2), D(2,2)
  INTEGER :: J(2), INFO

  A = Z_ZERO
  U = Z_ZERO
  Z = Z_ZERO
  J = 0
  INFO = 0

  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A11='
  READ (INPUT_UNIT,*) A(1,1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A21='
  READ (INPUT_UNIT,*) A(2,1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A12='
  READ (INPUT_UNIT,*) A(1,2)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A22='
  READ (INPUT_UNIT,*) A(2,2)
  B = A

  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'J_1='
  READ (INPUT_UNIT,*) J(1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'J_2='
  READ (INPUT_UNIT,*) J(2)

  CALL ZHSVD2(A, J, U, Z, INFO)
  WRITE (OUTPUT_UNIT,*) 'INFO=', INFO

  IF (INFO .GE. 0) THEN
     CALL UH2(U)
     CALL JZHJ2(Z, J)
  END IF

  WRITE (OUTPUT_UNIT,1) 'A11=', A(1,1)
  WRITE (OUTPUT_UNIT,1) 'A21=', A(2,1)
  WRITE (OUTPUT_UNIT,1) 'A12=', A(1,2)
  WRITE (OUTPUT_UNIT,1) 'A22=', A(2,2)

  WRITE (OUTPUT_UNIT,1) 'U11=', U(1,1)
  WRITE (OUTPUT_UNIT,1) 'U21=', U(2,1)
  WRITE (OUTPUT_UNIT,1) 'U12=', U(1,2)
  WRITE (OUTPUT_UNIT,1) 'U22=', U(2,2)

  WRITE (OUTPUT_UNIT,1) 'Z11=', Z(1,1)
  WRITE (OUTPUT_UNIT,1) 'Z21=', Z(2,1)
  WRITE (OUTPUT_UNIT,1) 'Z12=', Z(1,2)
  WRITE (OUTPUT_UNIT,1) 'Z22=', Z(2,2)

  C = U
  D = A
  C = MATMUL(C, D)
  D = Z
  D = MATMUL(C, D)
  C = B
  D = C - D
  WRITE (OUTPUT_UNIT,1) 'D11=', D(1,1)
  WRITE (OUTPUT_UNIT,1) 'D21=', D(2,1)
  WRITE (OUTPUT_UNIT,1) 'D12=', D(1,2)
  WRITE (OUTPUT_UNIT,1) 'D22=', D(2,2)

1 FORMAT(A,'(',ES25.17E3,',',ES25.17E3,')')
END PROGRAM ZTEST
