MODULE ZTYPES
  USE ATYPES
  IMPLICIT NONE

  ABSTRACT INTERFACE
     PURE FUNCTION ZMAG(APP, AQP, APQ, AQQ, JP, JQ)
       USE PARAMS
       IMPLICIT NONE
       COMPLEX(KIND=DWP), INTENT(IN) :: APP, AQP, APQ, AQQ
       INTEGER, INTENT(IN) :: JP, JQ
       REAL(KIND=DWP) :: ZMAG
     END FUNCTION ZMAG
  END INTERFACE

  ABSTRACT INTERFACE
     PURE FUNCTION ZCVG(APP, AQP, APQ, AQQ, JP, JQ)
       USE PARAMS
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: JP, JQ
       COMPLEX(KIND=DWP), INTENT(IN) :: APP, AQP, APQ, AQQ
       INTEGER :: ZCVG
     END FUNCTION ZCVG
  END INTERFACE

  TYPE ZPROC
     PROCEDURE(ZMAG), POINTER, NOPASS :: MAG
     PROCEDURE(VN_QSORT_CMP), POINTER, NOPASS :: CMP
     PROCEDURE(ZCVG), POINTER, NOPASS :: CVG
     PROCEDURE(ATRU), POINTER, NOPASS :: TRU
  END TYPE ZPROC

CONTAINS

END MODULE ZTYPES
