MODULE ZTYPES
  USE ATYPES
  IMPLICIT NONE

  ABSTRACT INTERFACE
     SUBROUTINE ASRT(NT, NN, NM, DZ, CMP, INFO)
       USE ATYPES
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: NT, NN, NM
       TYPE(AW), INTENT(INOUT), TARGET :: DZ(NM)
       PROCEDURE(VN_QSORT_CMP) :: CMP
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ASRT
  END INTERFACE

  ABSTRACT INTERFACE
     SUBROUTINE ANCP(NT, N, NN, NM, DZ, N_2, SL, STEP, INFO)
       USE ATYPES
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: NT, N, NN, NM, N_2
       TYPE(AW), INTENT(INOUT) :: DZ(NM)
       INTEGER, INTENT(OUT) :: SL, STEP(N_2), INFO
     END SUBROUTINE ANCP
  END INTERFACE

  ABSTRACT INTERFACE
#ifdef USE_EXTENDED
     FUNCTION ZMAG(N, P, Q, A, LDA, J)
#else
     PURE FUNCTION ZMAG(N, P, Q, A, LDA, J)
#endif
       USE PARAMS
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, P, Q, LDA, J(N)
       COMPLEX(KIND=DWP), INTENT(IN) :: A(LDA,N)
       REAL(KIND=DWP) :: ZMAG
     END FUNCTION ZMAG
  END INTERFACE

  TYPE ZPROC
     PROCEDURE(ZMAG), POINTER, NOPASS :: MAG
     PROCEDURE(VN_QSORT_CMP), POINTER, NOPASS :: CMP
     PROCEDURE(ASRT), POINTER, NOPASS :: SRT
     PROCEDURE(ANCP), POINTER, NOPASS :: NCP
     PROCEDURE(APQI), POINTER, NOPASS :: PQI
     PROCEDURE(ATRU), POINTER, NOPASS :: TRU
  END TYPE ZPROC

CONTAINS

END MODULE ZTYPES
