MODULE ZTYPES
  USE ATYPES
  IMPLICIT NONE

  ABSTRACT INTERFACE
     SUBROUTINE ASRT(NN, DZ, CMP, INFO)
       USE ATYPES
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: NN
       TYPE(AW), INTENT(INOUT), TARGET :: DZ(NN)
       PROCEDURE(VN_QSORT_CMP) :: CMP
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ASRT
  END INTERFACE

  ABSTRACT INTERFACE
     PURE FUNCTION ZMAG(N, P, Q, A, LDA, J)
       USE PARAMS
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, P, Q, LDA, J(N)
       COMPLEX(KIND=DWP), INTENT(IN) :: A(LDA,N)
       REAL(KIND=DWP) :: ZMAG
     END FUNCTION ZMAG
  END INTERFACE

  TYPE ZPROC
     PROCEDURE(ZMAG), POINTER, NOPASS :: MAG
     PROCEDURE(VN_QSORT_CMP), POINTER, NOPASS :: CMP
     PROCEDURE(ASRT), POINTER, NOPASS :: SRT
     PROCEDURE(APQI), POINTER, NOPASS :: PQI
     PROCEDURE(ATRU), POINTER, NOPASS :: TRU
  END TYPE ZPROC

CONTAINS

END MODULE ZTYPES
