  INTEGER, PARAMETER :: IFLAG_INVGJP =  1
  INTEGER, PARAMETER :: IFLAG_DGEQRF =  2
  INTEGER, PARAMETER :: IFLAG_ROWCYC =  4
  INTEGER, PARAMETER :: IFLAG_PPROCU =  8
  INTEGER, PARAMETER :: IFLAG_PPROCV = 16
  INTEGER, PARAMETER :: IFLAG_MAXFLG = 32

  DOUBLE PRECISION, PARAMETER :: ZERO =  0.0D+0
  DOUBLE PRECISION, PARAMETER :: HALF =  5.0D-1
  DOUBLE PRECISION, PARAMETER ::  ONE =  1.0D+0
  DOUBLE PRECISION, PARAMETER :: MONE = -1.0D+0
  DOUBLE PRECISION, PARAMETER ::  TWO =  2.0D+0
  DOUBLE PRECISION, PARAMETER :: MTWO = -2.0D+0
