SUBROUTINE GENDAT(LGIX, SEED, N, LAM, ISEED, NRANK, A, G, LDG, IPIV, JVEC, NPLUS, IPL, INVP, INFO)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: LGIX, SEED, N, LDG
  INTEGER, INTENT(OUT) :: ISEED(4), NRANK, IPIV(N), JVEC(N), NPLUS, IPL(N), INVP(N), INFO(2)
  REAL(KIND=8), INTENT(OUT) :: LAM(N), A(LDG,N), G(LDG,N)

  INTEGER :: JSEED(4), NPOS

  EXTERNAL :: SEEDIX, TXTLAM, GENLAM, XA2G

  INFO(1) = 0
  INFO(2) = 0

  CALL SEEDIX(SEED, ISEED, INFO(2))
  IF (INFO(2) .NE. 0) THEN
     INFO(1) = 10
     RETURN
  END IF
  JSEED = ISEED

  SELECT CASE (LGIX)
  CASE (1)
    CALL TXTLAM(N, JSEED, LAM, NPOS, INFO(2))
    IF (INFO(2) .NE. 0) INFO(1) = 21
  CASE (2)
    CALL GENLAM(N, JSEED, LAM, NPOS, INFO(2))
    IF (INFO(2) .NE. 0) INFO(1) = 22
  CASE DEFAULT
    INFO(1) = 20
    INFO(2) = LGIX
  END SELECT
  IF (INFO(1) .NE. 0) RETURN

  CALL XA2G(N, LAM, JSEED, NRANK, A, G, LDG, IPIV, JVEC, NPLUS, IPL, INVP, INFO)
  IF ((INFO(1) .EQ. 0) .AND. (NPLUS .NE. NPOS)) THEN
     INFO(1) = 30
     INFO(2) = NPOS
  END IF

END SUBROUTINE GENDAT
