SUBROUTINE GENLAM(N, ISEED, LAM, NPOS, INFO)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: N
  INTEGER, INTENT(INOUT) :: ISEED(4)
  REAL(KIND=8), INTENT(OUT) :: LAM(N)
  INTEGER, INTENT(OUT) :: NPOS, INFO

  REAL(KIND=8), PARAMETER :: ZERO = +0.0E+0_8, ONE = +1.0E+0_8

  INTEGER :: IDIST, I
  REAL(KIND=8) :: EPS, SCAL
  CHARACTER(LEN=256) :: CAS

  REAL(KIND=8), EXTERNAL :: DLARND
  EXTERNAL :: SEEDOK

  CALL SEEDOK(ISEED, I)

  IF (N .LT. 0) THEN
    INFO = -1
  ELSE IF (I .NE. 0) THEN
    INFO = -2
  ELSE IF (COMMAND_ARGUMENT_COUNT() .NE. 9) THEN
    INFO = -3
  ELSE
    INFO = 0
  END IF
  IF (INFO .NE. 0) RETURN

  CALL GET_COMMAND_ARGUMENT(7, CAS)
  READ (CAS,*) IDIST
  IF ((IDIST .LT. 1) .OR. (IDIST .GT. 3)) THEN
    INFO = 1
    RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(8, CAS)
  READ (CAS,*) EPS
  IF (EPS .LE. ZERO) THEN
    INFO = 2
    RETURN
  END IF

  CALL GET_COMMAND_ARGUMENT(9, CAS)
  READ (CAS,*) SCAL
  IF (SCAL .EQ. ZERO) THEN
    INFO = 3
    RETURN
  END IF

  NPOS = 0
  I = 1

  DO WHILE (I .LE. N)
    LAM(I) = DLARND(IDIST, ISEED)
    IF (ABS(LAM(I)) .GT. EPS) THEN
      IF (LAM(I) .GT. ZERO) NPOS = NPOS + 1
      I = I + 1
    END IF
  END DO

  IF (SCAL .NE. ONE) THEN
    DO I = 1, N
      LAM(I) = LAM(I) * SCAL
    END DO
  END IF

END SUBROUTINE GENLAM
