PROGRAM DPRINT
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
  IMPLICIT NONE
  INTEGER, PARAMETER :: ARL = 256
  CHARACTER(LEN=ARL) :: AR
  INTEGER :: N, U, I, INFO
  INTEGER(KIND=INT64), ALLOCATABLE :: J(:)
  DOUBLE PRECISION, ALLOCATABLE :: G(:,:), H(:,:), GH(:,:)
  DOUBLE COMPLEX, ALLOCATABLE :: Z(:,:)
  EXTERNAL :: BFOPEN, DBRD2, JBRD1, ZBWR2
  CALL GET_COMMAND_ARGUMENT(2, AR, STATUS=INFO)
  IF (INFO .NE. 0) STOP 'dprint.exe FN N'
  READ (AR,*) N
  IF (N .LE. 0) STOP 'N <= 0'
  CALL GET_COMMAND_ARGUMENT(1, AR, STATUS=INFO)
  IF (INFO .NE. 0) STOP 'dprint.exe FN N'
  CALL BFOPEN(TRIM(AR)//'.Y', 'RO', U, INFO)
  IF (INFO .NE. 0) STOP 'BFOPEN(G)'
  ALLOCATE(G(N,N))
  CALL DBRD2(U, N, N, G, N, INFO)
  CLOSE(U)
  IF (INFO .NE. 0) STOP 'DBRD2(G)'
  CALL BFOPEN(TRIM(AR)//'.J', 'RO', U, INFO)
  IF (INFO .NE. 0) STOP 'BFOPEN(J)'
  ALLOCATE(J(N))
  CALL JBRD1(U, N, J, INFO)
  CLOSE(U)
  IF (INFO .NE. 0) STOP 'JBRD1(J)'
  DO I = 1, N
     DO U = 1, N
        WRITE (UNIT=*,FMT=1,ADVANCE='NO') G(I,U)
     END DO
     WRITE (*,*)
  END DO
  DO I = 1, N
     WRITE (UNIT=*,FMT='(I3)',ADVANCE='NO') J(I)
  END DO
  WRITE (*,*)
  ALLOCATE(H(N,N))
  H = TRANSPOSE(G)
  DO I = 1, N
     IF (J(I) .EQ. -1_INT64) THEN
        DO U = 1, N
           H(I,U) = -H(I,U)
        END DO
     END IF
  END DO
  ALLOCATE(GH(N,N))
  GH = MATMUL(G, H)
  DO I = 1, N
     DO U = 1, N
        WRITE (UNIT=*,FMT=1,ADVANCE='NO') GH(I,U)
     END DO
     WRITE (*,*)
  END DO
  DEALLOCATE(GH)
  DEALLOCATE(H)
  DEALLOCATE(J)
  ALLOCATE(Z(N,N))
  DO U = 1, N
     DO I = 1, N
        Z(U,I) = DCMPLX(G(U,I), 0.0D0)
     END DO
  END DO
  DEALLOCATE(G)
  CALL BFOPEN(TRIM(AR)//'.Z', 'WO', U, INFO)
  IF (INFO .NE. 0) STOP 'BFOPEN(Z)'
  CALL ZBWR2(U, N, N, Z, N, INFO)
  CLOSE(U)
  DEALLOCATE(Z)
  IF (INFO .NE. 0) STOP 'ZBWR2(Z)'
1 FORMAT(ES26.17E3)
END PROGRAM DPRINT
