PROGRAM KINDS
  USE, INTRINSIC :: ISO_FORTRAN_ENV
  IMPLICIT NONE

  INTEGER :: CK, IK, LK, RK, I

  CK = SIZE(CHARACTER_KINDS)
  IK = SIZE(INTEGER_KINDS)
  LK = SIZE(LOGICAL_KINDS)
  RK = SIZE(REAL_KINDS)

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'CHARACTER_KINDS(', CK, ') = (/'
  DO I = 1, CK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') CHARACTER_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') CHARACTER_KINDS(CK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'INTEGER_KINDS(', IK, ')   = (/'
  DO I = 1, IK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') INTEGER_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') INTEGER_KINDS(IK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'LOGICAL_KINDS(', LK, ')   = (/'
  DO I = 1, LK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') LOGICAL_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') LOGICAL_KINDS(LK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'REAL_KINDS(', RK, ')      = (/'
  DO I = 1, RK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') REAL_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') REAL_KINDS(RK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT8    = ', INT8
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT16   = ', INT16
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT32   = ', INT32
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT64   = ', INT64
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL32  = ', REAL32
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL64  = ', REAL64
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL128 = ', REAL128

  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(CHARACTER)        = ', KIND(' ')
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(INTEGER)          = ', KIND(0)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(LOGICAL)          = ', KIND(.FALSE.)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(REAL)             = ', KIND(0.0E0)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(DOUBLE PRECISION) = ', KIND(0.0D0)
END PROGRAM KINDS
