PROGRAM kinds
  USE, INTRINSIC :: iso_c_binding
  USE, INTRINSIC :: iso_fortran_env
  IMPLICIT NONE

  INTEGER :: CK, IK, LK, RK, I

  CK = SIZE(CHARACTER_KINDS)
  IK = SIZE(INTEGER_KINDS)
  LK = SIZE(LOGICAL_KINDS)
  RK = SIZE(REAL_KINDS)

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'CHARACTER_KINDS(', CK, ') = (/'
  DO I = 1, CK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') CHARACTER_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') CHARACTER_KINDS(CK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'INTEGER_KINDS(', IK, ')   = (/'
  DO I = 1, IK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') INTEGER_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') INTEGER_KINDS(IK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'LOGICAL_KINDS(', LK, ')   = (/'
  DO I = 1, LK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') LOGICAL_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') LOGICAL_KINDS(LK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I1,A)',ADVANCE='NO') 'REAL_KINDS(', RK, ')      = (/'
  DO I = 1, RK-1
     WRITE (OUTPUT_UNIT,'(I2,A)',ADVANCE='NO') REAL_KINDS(I), ','
  END DO
  WRITE (OUTPUT_UNIT,'(I2,A)') REAL_KINDS(RK), ' /)'

  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT8    = ', INT8
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT16   = ', INT16
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT32   = ', INT32
  WRITE (OUTPUT_UNIT,'(A,I2)') 'INT64   = ', INT64
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL32  = ', REAL32
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL64  = ', REAL64
  WRITE (OUTPUT_UNIT,'(A,I2)') 'REAL128 = ', REAL128

  WRITE (OUTPUT_UNIT,'(A,I2)') 'c_float       = ', c_float
  WRITE (OUTPUT_UNIT,'(A,I2)') 'c_double      = ', c_double
  WRITE (OUTPUT_UNIT,'(A,I2)') 'c_long_double = ', c_long_double
  
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(CHARACTER)        = ', KIND(' ')
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(INTEGER)          = ', KIND(0)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(LOGICAL)          = ', KIND(.FALSE.)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(REAL)             = ', KIND(0.0E0)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'KIND(DOUBLE PRECISION) = ', KIND(0.0D0)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(INT8)          = ', RADIX(0_INT8)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(INT8)         = ', DIGITS(0_INT8)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'RANGE(INT8)          = ', RANGE(0_INT8)
  WRITE (OUTPUT_UNIT,*) 'HUGE(INT8)       = ', HUGE(0_INT8)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(INT16)         = ', RADIX(0_INT16)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(INT16)        = ', DIGITS(0_INT16)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'RANGE(INT16)         = ', RANGE(0_INT16)
  WRITE (OUTPUT_UNIT,*) 'HUGE(INT16)      = ', HUGE(0_INT16)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(INT32)         = ', RADIX(0_INT32)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(INT32)        = ', DIGITS(0_INT32)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'RANGE(INT32)         = ', RANGE(0_INT32)
  WRITE (OUTPUT_UNIT,*) 'HUGE(INT32)      = ', HUGE(0_INT32)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(INT64)         = ', RADIX(0_INT64)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(INT64)        = ', DIGITS(0_INT64)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'RANGE(INT64)         = ', RANGE(0_INT64)
  WRITE (OUTPUT_UNIT,*) 'HUGE(INT64)      = ', HUGE(0_INT64)

  ! uncomment for GNU Fortran; INTEGER(16) = INT128 (undefined)
  ! WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(16)            = ', RADIX(0_16)
  ! WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(16)           = ', DIGITS(0_16)
  ! WRITE (OUTPUT_UNIT,'(A,I3)') 'RANGE(16)            = ', RANGE(0_16)
  ! WRITE (OUTPUT_UNIT,*) 'HUGE(16)         = ', HUGE(0_16)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(REAL32)        = ', RADIX(0.0_REAL32)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'PRECISION(REAL32)    = ', PRECISION(0.0_REAL32)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(REAL32)       = ', DIGITS(0.0_REAL32)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'RANGE(REAL32)        = ', RANGE(0.0_REAL32)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MINEXPONENT(REAL32)  = ', MINEXPONENT(0.0_REAL32)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MAXEXPONENT(REAL32)  = ', MAXEXPONENT(0.0_REAL32)
  WRITE (OUTPUT_UNIT,*) 'TINY(REAL32)     = ', TINY(0.0_REAL32)
  WRITE (OUTPUT_UNIT,*) 'EPSILON(REAL32)  = ', EPSILON(0.0_REAL32)
  WRITE (OUTPUT_UNIT,*) 'HUGE(REAL32)     = ', HUGE(0.0_REAL32)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(REAL64)        = ', RADIX(0.0_REAL64)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'PRECISION(REAL64)    = ', PRECISION(0.0_REAL64)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(REAL64)       = ', DIGITS(0.0_REAL64)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'RANGE(REAL64)        = ', RANGE(0.0_REAL64)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MINEXPONENT(REAL64)  = ', MINEXPONENT(0.0_REAL64)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MAXEXPONENT(REAL64)  = ', MAXEXPONENT(0.0_REAL64)
  WRITE (OUTPUT_UNIT,*) 'TINY(REAL64)     = ', TINY(0.0_REAL64)
  WRITE (OUTPUT_UNIT,*) 'EPSILON(REAL64)  = ', EPSILON(0.0_REAL64)
  WRITE (OUTPUT_UNIT,*) 'HUGE(REAL64)     = ', HUGE(0.0_REAL64)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(REAL128)       = ', RADIX(0.0_REAL128)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'PRECISION(REAL128)   = ', PRECISION(0.0_REAL128)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(REAL128)      = ', DIGITS(0.0_REAL128)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'RANGE(REAL128)       = ', RANGE(0.0_REAL128)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MINEXPONENT(REAL128) = ', MINEXPONENT(0.0_REAL128)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MAXEXPONENT(REAL128) = ', MAXEXPONENT(0.0_REAL128)
  WRITE (OUTPUT_UNIT,*) 'TINY(REAL128)    = ', TINY(0.0_REAL128)
  WRITE (OUTPUT_UNIT,*) 'EPSILON(REAL128) = ', EPSILON(0.0_REAL128)
  WRITE (OUTPUT_UNIT,*) 'HUGE(REAL128)    = ', HUGE(0.0_REAL128)

  WRITE (OUTPUT_UNIT,'(A,I2)') 'RADIX(c_long_double)       = ', RADIX(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'PRECISION(c_long_double)   = ', PRECISION(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,'(A,I3)') 'DIGITS(c_long_double)      = ', DIGITS(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'RANGE(c_long_double)       = ', RANGE(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MINEXPONENT(c_long_double) = ', MINEXPONENT(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,'(A,I6)') 'MAXEXPONENT(c_long_double) = ', MAXEXPONENT(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,*) 'TINY(c_long_double)    = ', TINY(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,*) 'EPSILON(c_long_double) = ', EPSILON(0.0_c_long_double)
  WRITE (OUTPUT_UNIT,*) 'HUGE(c_long_double)    = ', HUGE(0.0_c_long_double)
END PROGRAM kinds
