MODULE PARAMS
#ifndef NDEBUG
  USE, INTRINSIC :: IEEE_ARITHMETIC
  USE, INTRINSIC :: IEEE_FEATURES
#endif
  USE, INTRINSIC :: ISO_C_BINDING
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT
  USE VN_TYPES_F
  IMPLICIT NONE

  INTEGER, PARAMETER :: UINP = INPUT_UNIT
  INTEGER, PARAMETER :: UOUT = OUTPUT_UNIT
  INTEGER, PARAMETER :: ULOG = ERROR_UNIT

  ! Max file name length.
  INTEGER, PARAMETER :: FNL = 252

#include "vn_params.F90"

CONTAINS
END MODULE PARAMS
