MODULE params
  USE, INTRINSIC :: iso_fortran_env, ONLY: INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT
  IMPLICIT NONE

  INTEGER, PARAMETER :: SWP = KIND(0E0)
  INTEGER, PARAMETER :: DWP = KIND(0D0)
  INTEGER, PARAMETER :: QWP = 16

  ! Max file name length.
  INTEGER, PARAMETER :: FNL = 252

  INTEGER(KIND=SWP), PARAMETER :: S_QNAN_MASK = 2143289344_SWP
  INTEGER(KIND=DWP), PARAMETER :: D_QNAN_MASK = 9221120237041090560_DWP

  REAL(KIND=DWP), PARAMETER :: D_ZERO =  0.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_MZERO= -0.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_ONE  =  1.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_MONE = -1.0_DWP

  COMPLEX(KIND=DWP), PARAMETER :: Z_ZERO = (D_ZERO, D_ZERO)
  COMPLEX(KIND=DWP), PARAMETER :: Z_ONE  = (D_ONE , D_ZERO)

  REAL(KIND=DWP), PARAMETER :: TWOF = SQRT(HUGE(D_ZERO))
  REAL(KIND=DWP), PARAMETER :: MINF = REAL(Z'0000000000000001',DWP)

CONTAINS

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  PURE REAL(KIND=DWP) FUNCTION QUIET_NAN(PAYLOAD)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: PAYLOAD

    QUIET_NAN = TRANSFER(IOR(INT(PAYLOAD,DWP), D_QNAN_MASK), 0.0_DWP)
  END FUNCTION QUIET_NAN

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

END MODULE params
