MODULE params
#ifdef USE_NVIDIA
  USE, INTRINSIC :: iso_fortran_env, ONLY: INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT
#else
  USE, INTRINSIC :: iso_fortran_env, ONLY: INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT, REAL128
#endif
  IMPLICIT NONE

  INTEGER, PARAMETER :: SWP = KIND(0E0)
  INTEGER, PARAMETER :: DWP = KIND(0D0)
#ifdef USE_NVIDIA
  INTEGER, PARAMETER :: QWP = DWP
#else
  INTEGER, PARAMETER :: QWP = REAL128
#endif

  ! Max file name length.
  INTEGER, PARAMETER :: FNL = 252

  INTEGER(KIND=SWP), PARAMETER :: S_QNAN_MASK = 2143289344_SWP
  INTEGER(KIND=DWP), PARAMETER :: D_QNAN_MASK = 9221120237041090560_DWP

  REAL(KIND=DWP), PARAMETER :: D_ZERO =  0.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_MZERO= -0.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_ONE  =  1.0_DWP
  REAL(KIND=DWP), PARAMETER :: D_MONE = -1.0_DWP

  COMPLEX(KIND=DWP), PARAMETER :: Z_ZERO = (D_ZERO, D_ZERO)
  COMPLEX(KIND=DWP), PARAMETER :: Z_ONE  = (D_ONE , D_ZERO)

  REAL(KIND=DWP), PARAMETER :: TWOF = SQRT(HUGE(D_ZERO))
  REAL(KIND=DWP), PARAMETER :: MINF = REAL(Z'0000000000000001',DWP)
#ifdef USE_TEST
  REAL(KIND=DWP), PARAMETER :: TH1FIX = D_ONE
#else
  REAL(KIND=DWP), PARAMETER :: TH1FIX = 4.0_DWP / 5
#endif

#if defined(USE_ABSOFT) || defined(USE_NVIDIA)
  INTEGER, PARAMETER :: EH =  1024
  INTEGER, PARAMETER :: ET = -1021
#else
  INTEGER, PARAMETER :: EH = EXPONENT(HUGE(D_ZERO))
  INTEGER, PARAMETER :: ET = EXPONENT(TINY(D_ZERO))
#endif
CONTAINS
END MODULE params
