MODULE H5DATA
  USE H5LT
  USE HDF5
  IMPLICIT NONE

  INTEGER, PARAMETER :: IDALEN = 4
  INTEGER, PARAMETER :: TIMLEN = 4

CONTAINS

  SUBROUTINE READH0(GID, IDADIM, INFO)
    IMPLICIT NONE

    INTEGER(HID_T), INTENT(IN) :: GID
    INTEGER, INTENT(OUT) :: IDADIM(IDALEN), INFO(2)

    INTEGER(HSIZE_T) :: DIMS1(1)

    INFO = 0

    DIMS1(1) = IDALEN
    CALL H5LTREAD_DATASET_INT_F(GID, 'IDADIM', IDADIM, DIMS1, INFO(2))
    IF (INFO(2) .NE. 0) INFO(1) = 1
  END SUBROUTINE READH0

  SUBROUTINE READH1(GID, M, N, G, LDG, JVEC, INFO)
    IMPLICIT NONE

    INTEGER(HID_T), INTENT(IN) :: GID
    INTEGER, INTENT(IN) :: M, N, LDG
    DOUBLE PRECISION, INTENT(OUT) :: G(LDG, N)
    INTEGER, INTENT(OUT) :: JVEC(N), INFO(2)

    INTEGER(HSIZE_T) :: DIMS1(1), DIMS2(2)

    INFO = 0

    DIMS2(1) = LDG
    DIMS2(2) = N
    CALL H5LTREAD_DATASET_DOUBLE_F(GID, 'G', G, DIMS2, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 1
       RETURN
    END IF

    DIMS1(1) = N
    CALL H5LTREAD_DATASET_INT_F(GID, 'JVEC', JVEC, DIMS1, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 2
       RETURN
    END IF
  END SUBROUTINE READH1

  SUBROUTINE READH2(GID, N, IPL, INVP, INFO)
    IMPLICIT NONE

    INTEGER(HID_T), INTENT(IN) :: GID
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: IPL(N), INVP(N), INFO(2)

    INTEGER(HSIZE_T) :: DIMS1(1)

    INFO = 0

    DIMS1(1) = N
    CALL H5LTREAD_DATASET_INT_F(GID, 'IPL', IPL, DIMS1, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 1
       RETURN
    END IF

    DIMS1(1) = N
    CALL H5LTREAD_DATASET_INT_F(GID, 'INVP', INVP, DIMS1, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 2
       RETURN
    END IF
  END SUBROUTINE READH2

  SUBROUTINE DUMPH5(GID, M, N, G, LDG, JVEC, NPLUS, U, LDU, V, LDV, Q, LDQ, TOL, IFLAGS, STATUS, TCPU, INFO)
    IMPLICIT NONE

    INTEGER(HID_T), INTENT(IN) :: GID
    INTEGER, INTENT(IN) :: M, N, LDG, JVEC(N), NPLUS, LDU, LDV, LDQ, IFLAGS, STATUS
    DOUBLE PRECISION, INTENT(IN) :: G(LDG,N), U(LDU,M), V(LDV,N), Q(LDQ,M), TOL, TCPU(TIMLEN)
    INTEGER, INTENT(OUT) :: INFO(2)

    INTEGER(HSIZE_T) :: DIMS1(1), DIMS2(2)
    INTEGER(SIZE_T) :: ATRLEN

    INTEGER :: IDUMMY(3)
    DOUBLE PRECISION :: DDUMMY(1)

    INFO = 0

    IF (LDG .GT. 0) THEN
       DIMS2(1) = LDG
       DIMS2(2) = N
       CALL H5LTMAKE_DATASET_DOUBLE_F(GID, 'G', 2, DIMS2, G, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  1
          RETURN
       END IF

       ATRLEN = 3
       IDUMMY(1) = M
       IDUMMY(2) = N
       IDUMMY(3) = LDG
       CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'G', 'dims', IDUMMY, ATRLEN, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  2
          RETURN
       END IF

       DIMS1(1) = N
       CALL H5LTMAKE_DATASET_INT_F(GID, 'JVEC', 1, DIMS1, JVEC, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  3
          RETURN
       END IF

       ATRLEN = 3
       IDUMMY(1) = N
       IDUMMY(2) = NPLUS
       IDUMMY(3) = M
       CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'JVEC', 'dims', IDUMMY, ATRLEN, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  4
          RETURN
       END IF
    END IF

    IF (LDU .GT. 0) THEN
       DIMS2(1) = LDU
       DIMS2(2) = M
       CALL H5LTMAKE_DATASET_DOUBLE_F(GID, 'U', 2, DIMS2, U, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  5
          RETURN
       END IF

       ATRLEN = 3
       IDUMMY(1) = M
       IDUMMY(2) = M
       IDUMMY(3) = LDU
       CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'U', 'dims', IDUMMY, ATRLEN, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  6
          RETURN
       END IF
    END IF

    IF (LDV .GT. 0) THEN
       DIMS2(1) = LDV
       DIMS2(2) = N
       CALL H5LTMAKE_DATASET_DOUBLE_F(GID, 'V', 2, DIMS2, V, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  7
          RETURN
       END IF

       ATRLEN = 3
       IDUMMY(1) = N
       IDUMMY(2) = N
       IDUMMY(3) = LDV
       CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'V', 'dims', IDUMMY, ATRLEN, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  8
          RETURN
       END IF
    END IF

    IF (LDQ .GT. 0) THEN
       DIMS2(1) = LDQ
       DIMS2(2) = M
       CALL H5LTMAKE_DATASET_DOUBLE_F(GID, 'Q', 2, DIMS2, Q, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) =  9
          RETURN
       END IF

       ATRLEN = 3
       IDUMMY(1) = M
       IDUMMY(2) = M
       IDUMMY(3) = LDQ
       CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'Q', 'dims', IDUMMY, ATRLEN, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) = 10
          RETURN
       END IF
    END IF

    DIMS1(1) = TIMLEN
    CALL H5LTMAKE_DATASET_DOUBLE_F(GID, 'Tcpu', 1, DIMS1, TCPU, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 11
       RETURN
    END IF

    ATRLEN = 1
    IDUMMY(1) = TIMLEN
    CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'Tcpu', 'dims', IDUMMY, ATRLEN, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 12
       RETURN
    END IF

    DIMS1(1) = 2
    IDUMMY(1) = STATUS
    IDUMMY(2) = IFLAGS
    CALL H5LTMAKE_DATASET_INT_F(GID, 'STATUS', 1, DIMS1, IDUMMY, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 13
       RETURN
    END IF

    ATRLEN = 1
    DDUMMY(1) = TOL
    CALL H5LTSET_ATTRIBUTE_DOUBLE_F(GID, 'STATUS', 'tol', DDUMMY, ATRLEN, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 14
       RETURN
    END IF

    ATRLEN = 1
    IDUMMY(1) = 2
    CALL H5LTSET_ATTRIBUTE_INT_F(GID, 'STATUS', 'dims', IDUMMY, ATRLEN, INFO(2))
    IF (INFO(2) .NE. 0) THEN
       INFO(1) = 15
       RETURN
    END IF
  END SUBROUTINE DUMPH5
END MODULE H5DATA
