PROGRAM DTEST
  USE DTRANSF
  IMPLICIT NONE

  REAL(KIND=DWP) :: A(2,2), U(2,2), Z(2,2)
  INTEGER :: J(2), INFO

  A = D_ZERO
  U = D_ZERO
  Z = D_ZERO
  J = 0
  INFO = 0

  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A11='
  READ (INPUT_UNIT,*) A(1,1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A21='
  READ (INPUT_UNIT,*) A(2,1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A12='
  READ (INPUT_UNIT,*) A(1,2)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'A22='
  READ (INPUT_UNIT,*) A(2,2)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'J_1='
  READ (INPUT_UNIT,*) J(1)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'J_2='
  READ (INPUT_UNIT,*) J(2)

  CALL DHSVD2(A, J, U, Z, INFO)
  WRITE (OUTPUT_UNIT,*) 'INFO=', INFO

  IF (INFO .GE. 0) THEN
     CALL UT2(U)
     CALL JZTJ2(Z, J)
  END IF

  WRITE (OUTPUT_UNIT,*) 'A11=', A(1,1)
  WRITE (OUTPUT_UNIT,*) 'A21=', A(2,1)
  WRITE (OUTPUT_UNIT,*) 'A12=', A(1,2)
  WRITE (OUTPUT_UNIT,*) 'A22=', A(2,2)

  WRITE (OUTPUT_UNIT,*) 'U11=', U(1,1)
  WRITE (OUTPUT_UNIT,*) 'U21=', U(2,1)
  WRITE (OUTPUT_UNIT,*) 'U12=', U(1,2)
  WRITE (OUTPUT_UNIT,*) 'U22=', U(2,2)

  WRITE (OUTPUT_UNIT,*) 'Z11=', Z(1,1)
  WRITE (OUTPUT_UNIT,*) 'Z21=', Z(2,1)
  WRITE (OUTPUT_UNIT,*) 'Z12=', Z(1,2)
  WRITE (OUTPUT_UNIT,*) 'Z22=', Z(2,2)
END PROGRAM DTEST
