MODULE DTYPES
  USE ATYPES
  IMPLICIT NONE

  ABSTRACT INTERFACE
     SUBROUTINE ASRT(NT, NN, DZ, CMP, INFO)
       USE ATYPES
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: NT, NN
       TYPE(AW), INTENT(INOUT), TARGET :: DZ(NN)
       PROCEDURE(VN_QSORT_CMP) :: CMP
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE ASRT
  END INTERFACE

  ABSTRACT INTERFACE
     SUBROUTINE ANCP(NT, NN, DZ, N_2, SL, STEP, INFO)
       USE ATYPES
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: NT, NN, N_2
       TYPE(AW), INTENT(INOUT) :: DZ(NN)
       INTEGER, INTENT(OUT) :: SL, STEP(N_2), INFO
     END SUBROUTINE ANCP
  END INTERFACE

  ABSTRACT INTERFACE
     PURE FUNCTION DMAG(N, P, Q, A, LDA, J)
       USE PARAMS
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, P, Q, LDA, J(N)
       REAL(KIND=DWP), INTENT(IN) :: A(LDA,N)
       REAL(KIND=DWP) :: DMAG
     END FUNCTION DMAG
  END INTERFACE

  TYPE DPROC
     PROCEDURE(DMAG), POINTER, NOPASS :: MAG
     PROCEDURE(VN_QSORT_CMP), POINTER, NOPASS :: CMP
     PROCEDURE(ASRT), POINTER, NOPASS :: SRT
     PROCEDURE(ANCP), POINTER, NOPASS :: NCP
     PROCEDURE(APQI), POINTER, NOPASS :: PQI
     PROCEDURE(ATRU), POINTER, NOPASS :: TRU
  END TYPE DPROC

CONTAINS

END MODULE DTYPES
