MODULE DTYPES
  USE ATYPES
  IMPLICIT NONE

  ABSTRACT INTERFACE
     PURE FUNCTION DMAG(N, P, Q, A, LDA, J)
       USE PARAMS
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N, P, Q, LDA, J(N)
       REAL(KIND=DWP), INTENT(IN) :: A(LDA,N)
       REAL(KIND=DWP) :: DMAG
     END FUNCTION DMAG
  END INTERFACE

  TYPE DPROC
     PROCEDURE(DMAG), POINTER, NOPASS :: MAG
     PROCEDURE(VN_QSORT_CMP), POINTER, NOPASS :: CMP
     PROCEDURE(APQI), POINTER, NOPASS :: PQI
     PROCEDURE(ATRU), POINTER, NOPASS :: TRU
  END TYPE DPROC

CONTAINS

END MODULE DTYPES
