SHELL=/bin/bash
ifdef NDEBUG
DEBUG=
else # DEBUG
DEBUG=g
endif # ?NDEBUG
RM=rm -rfv
AR=ar
ARFLAGS=rsv
CPUFLAGS=-DUSE_ABSOFT -DUSE_X64 -fpic -m64 -march=host -openmp
FORFLAGS=$(CPUFLAGS) -ea -en -et
FPUFLAGS=-OPT:roundoff=0 -safefp
FC=af95
ifdef NDEBUG
OPTFLAGS=-O$(NDEBUG) #-DUSE_FAST
DBGFLAGS=-DNDEBUG #-DUSE_TEST
DBGFFLAGS=$(DBGFLAGS)
FPUFFLAGS=$(FPUFLAGS)
else # DEBUG
OPTFLAGS=-O$(DEBUG)
DBGFLAGS=-$(DEBUG) -gdwarf2 -v
DBGFFLAGS=$(DBGFLAGS) -Rb -Rc -Rs -Rp
endif # ?NDEBUG
OPTFFLAGS=$(OPTFLAGS)
FPUFFLAGS=$(FPUFLAGS)
LIBFLAGS=-D_GNU_SOURCE -I. -I../shared
LDFLAGS=-L. -l$(TYPE)jk$(DEBUG) -L../shared -ljk$(DEBUG)
LDFLAGS += -lpthread -lm -ldl
FFLAGS=$(OPTFFLAGS) $(DBGFFLAGS) $(LIBFLAGS) $(FORFLAGS) $(FPUFFLAGS)
