PURE SUBROUTINE DMKLDM(M, LDA)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: M
  INTEGER, INTENT(OUT) :: LDA

  INTEGER :: R

  LDA = M
  IF (M .LT. 0) RETURN

  R = MOD(LDA, 8)
  IF (R .NE. 0) LDA = LDA + (8 - R)
END SUBROUTINE DMKLDM
