SUBROUTINE INVGJP(NROW, NCOLR, G, LDG, JVEC, IPL, INVP)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: NROW, NCOLR, LDG
  DOUBLE PRECISION, INTENT(INOUT) :: G(LDG,NCOLR)
  INTEGER, INTENT(INOUT) :: JVEC(NCOLR), IPL(NCOLR), INVP(NCOLR)

  INTEGER :: I, IP, JTEMP

  EXTERNAL :: DSWAP

  DO I = 1, NCOLR
    IF (INVP(I) .NE. I) THEN
       IP = INVP(I)

       CALL DSWAP(NROW, G(1,I), 1, G(1,IP), 1)
       JTEMP = JVEC(I)
       JVEC(I) = JVEC(IP)
       JVEC(IP) = JTEMP
       
       IPL(IP) = IPL(I)
       INVP(IPL(I)) = IP
    END IF
 END DO
END SUBROUTINE INVGJP
