PROGRAM JK
#ifndef NDEBUG
  USE, INTRINSIC :: IEEE_ARITHMETIC
  USE, INTRINSIC :: IEEE_FEATURES
#endif
  USE H5DATA
  USE JK1

  IMPLICIT NONE

  INTEGER, PARAMETER :: ARGLEN = 256

  CHARACTER(LEN=ARGLEN) :: AH5F, AH5G, AH5R
  INTEGER :: IFLAGS

  INTEGER(HID_T) :: FID, GID

  INTEGER :: IDADIM(IDALEN)
  INTEGER :: LDG, N, NRANK, NPLUS
  EQUIVALENCE (IDADIM(1), LDG), (IDADIM(2), N), (IDADIM(3), NRANK), (IDADIM(4), NPLUS)
  INTEGER :: LDU, LDV

  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: G, Q, U, V
  INTEGER, DIMENSION(:), ALLOCATABLE :: JVEC, IPL, INVP
  DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: TAU, WORK

  DOUBLE PRECISION :: WORK1(1)
  INTEGER :: LWORK, LENWRK, I

  CHARACTER(LEN=1) :: UPLO
  DOUBLE PRECISION :: TOL
  INTEGER :: NSWEEP, STATUS

  DOUBLE PRECISION :: TSTART, TSTOP, TCPU(TIMLEN)
  LOGICAL :: FEXIST
  INTEGER :: INFO(2)

  EXTERNAL :: DGEQRF, DGEQLF
  EXTERNAL :: DORGQR, DORGQL
  EXTERNAL :: DLACPY, DLASET
  EXTERNAL :: DGEQRFP, DSCAL

  ! EXECUTABLE STATEMENTS

#ifndef NDEBUG
  CALL IEEE_SET_HALTING_MODE(IEEE_USUAL, .TRUE.)
#endif

  TCPU = ZERO

  CALL READCL(AH5F, AH5G, AH5R, IFLAGS, INFO)
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1), INFO(2)
     STOP 'Error reading the command line!'
  END IF

  INQUIRE(FILE=AH5F, EXIST=FEXIST)
  IF (.NOT. FEXIST) STOP 'Input file does not exist!'

  CALL H5OPEN_F(INFO(1))
  IF (INFO(1) .NE. 0) STOP 'HDF5 not initialized!'

  CALL H5FOPEN_F(AH5F, H5F_ACC_RDONLY_F, FID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error opening the input file!'

  CALL H5GOPEN_F(FID, AH5G, GID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error opening the input group!'

  CALL READH0(GID, IDADIM, INFO)
  IF (INFO(1) .NE. 0) STOP 'Error reading IDADIM!'

  IF ((NPLUS .LT. 0) .OR. (NRANK .LE. 0) .OR. (N .LE. 0) .OR. (LDG .LE. 0)) STOP 'IDADIM invalid!'
  IF ((NPLUS .GT. NRANK) .OR. (NRANK .GT. N) .OR. (N .GT. LDG)) STOP 'IDADIM inconsistent!'

  CALL DMKLDM(N, LDU) ! LDU >= N
  CALL DMKLDM(NRANK, LDV) ! LDV >= NRANK

  ALLOCATE(G(LDG,NRANK))
  ALLOCATE(JVEC(NRANK))

  CALL READH1(GID, N, NRANK, G, LDG, JVEC, INFO)
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(2)
     STOP 'Error reading the input data!'
  end if
  IF (LDG .GT. N) CALL DLASET('A', LDG-N, NRANK, ZERO, ZERO, G(N+1,1), LDG)

  IF (IAND(IFLAGS, IFLAG_INVGJP) .NE. 0) THEN
     ALLOCATE(IPL(NRANK))
     ALLOCATE(INVP(NRANK))

     CALL READH2(GID, NRANK, IPL, INVP, INFO)
     IF (INFO(1) .NE. 0) THEN
        PRINT *, INFO(2)
        STOP 'Error reading the permutation data!'
     END IF
  END IF

  CALL H5GCLOSE_F(GID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error closing the input group!'

  CALL H5FCLOSE_F(FID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error closing the input file!'

  IF (IAND(IFLAGS, IFLAG_INVGJP) .NE. 0) THEN
     CALL CPU_TIME(TSTART)
     CALL INVGJP(N, NRANK, G, LDG, JVEC, IPL, INVP)
     CALL CPU_TIME(TSTOP)
     
     DEALLOCATE(INVP)
     DEALLOCATE(IPL)

     TCPU(1) = TSTOP - TSTART
     PRINT *, 'INVGJP=', TCPU(1), 's.'
  ELSE
     TCPU(1) = ZERO
  END IF

  ALLOCATE(Q(LDU,N))
  IF (LDU .GT. N) CALL DLASET('A', LDU-N, N, ZERO, ZERO, Q(N+1,1), LDU)

  ALLOCATE(TAU(MAX(1, MIN(N, NRANK))))

  LWORK = -1
  LENWRK = 1

  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     CALL DGEQRFP(N, NRANK, G, LDG, TAU, WORK1, LWORK, INFO(1))
  ELSE
     CALL DGEQLF(N, NRANK, G, LDG, TAU, WORK1, LWORK, INFO(1))
  END IF
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1)
     IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
        STOP 'Error in workspace query for DGEQRFP!'
     ELSE
        STOP 'Error in workspace query for DGEQLF!'
     END IF
  END IF

  LENWRK = MAX(LENWRK, MAX(1, CEILING(WORK1(1))))

  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     CALL DORGQR(N, N, NRANK, Q, LDU, TAU, WORK1, LWORK, INFO(1))
  ELSE
     CALL DORGQL(N, N, NRANK, Q, LDU, TAU, WORK1, LWORK, INFO(1))
  END IF
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1)
     IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
        STOP 'Error in workspace query for DORGQR!'
     ELSE
        STOP 'Error in workspace query for DORGQL!'
     END IF
  END IF

  LENWRK = MAX(LENWRK, MAX(1, CEILING(WORK1(1))))

  LWORK = LENWRK
  ALLOCATE(WORK(LWORK))

  CALL CPU_TIME(TSTART)
  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     CALL DGEQRFP(N, NRANK, G, LDG, TAU, WORK, LWORK, INFO(1))
  ELSE
     CALL DGEQLF(N, NRANK, G, LDG, TAU, WORK, LWORK, INFO(1))
  END IF
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1)
     IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
        STOP 'Error in DGEQRFP!'
     ELSE
        STOP 'Error in DGEQLF!'
     END IF
  END IF
  CALL CPU_TIME(TSTOP)
  TCPU(2) = TSTOP - TSTART
  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     PRINT *, 'DGEQRFP=', TCPU(2), 's.'
  ELSE
     PRINT *, 'DGEQLF=', TCPU(2), 's.'
  END IF

  CALL DLACPY('A', N, NRANK, G, LDG, Q, LDU)

  CALL CPU_TIME(TSTART)
  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     CALL DORGQR(N, N, NRANK, Q, LDU, TAU, WORK, LWORK, INFO(1))
  ELSE
     CALL DORGQL(N, N, NRANK, Q, LDU, TAU, WORK, LWORK, INFO(1))
  END IF
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1)
     IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
        STOP 'Error in DORGQR!'
     ELSE
        STOP 'Error in DORGQL!'
     END IF
  END IF
  CALL CPU_TIME(TSTOP)
  TCPU(3) = TSTOP - TSTART
  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     PRINT *, 'DORGQR=', TCPU(3), 's.'
  ELSE
     PRINT *, 'DORGQL=', TCPU(3), 's.'
  END IF

  DEALLOCATE(WORK)
  DEALLOCATE(TAU)

  IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
     UPLO = 'U'
     CALL DLASET('L', N-1, NRANK-1, ZERO, ZERO, G(2,1), LDG)
  ELSE
     UPLO = 'L'
     CALL DLASET('U', N-1, NRANK-1, ZERO, ZERO, G(1,2), LDG)
  END IF

  DO I = 1, NRANK
     IF (G(I,I) .EQ. ZERO) THEN
        STOP 'I refuse to work on a singular matrix!'
     ELSE IF (G(I,I) .LT. ZERO) THEN
        CALL DSCAL(N, MONE, Q(1,I), 1)
        IF (IAND(IFLAGS, IFLAG_DGEQRF) .NE. 0) THEN
           CALL DSCAL(NRANK-I+1, MONE, G(I,I), LDG)
        ELSE
           CALL DSCAL(I, MONE, G(I,1), LDG)
        END IF
     END IF
  END DO

  ALLOCATE(U(LDU,N))
  IF (LDU .GT. N) CALL DLASET('A', LDU-N, N, ZERO, ZERO, U(N+1,1), LDU)

  CALL DLASET('A', LDU, N, ZERO, ONE, U, LDU) ! U = I

  ALLOCATE(V(LDV,NRANK))
  IF (LDV .GT. NRANK) CALL DLASET('A', LDV-NRANK, NRANK, ZERO, ZERO, V(NRANK+1,1), LDV)

  CALL DLASET('A', LDV, NRANK, ZERO, ONE, V, LDV) ! V = I

  INQUIRE(FILE=AH5R, EXIST=FEXIST)
  IF (FEXIST) THEN
     CALL H5FOPEN_F(AH5R, H5F_ACC_RDWR_F, FID, INFO(1))
     IF (INFO(1) .NE. 0) STOP 'Error opening the output file!'
  ELSE
     CALL H5FCREATE_F(AH5R, H5F_ACC_TRUNC_F, FID, INFO(1))
     IF (INFO(1) .NE. 0) STOP 'Error creating the output file!'
  END IF

  TOL = EPSILON(ONE)
  NSWEEP = 30
  CALL CPU_TIME(TSTART)
  CALL DJKSVD(UPLO, N, NRANK, G, LDG, U, LDU, V, LDV, JVEC, NPLUS, TOL, NSWEEP, IFLAGS, INFO)
  CALL CPU_TIME(TSTOP)
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(1), INFO(2)
     PRINT *, 'Error in DJKSVD!'
  END IF
  TCPU(4) = TSTOP - TSTART
  PRINT *, 'DJKSVD=', TCPU(4), 's.'
  STATUS = INFO(2)
  PRINT *, 'DJKSVD:', STATUS

  CALL H5GCREATE_F(FID, AH5G, GID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error creating the output group!'

  CALL DUMPH5(GID, N, NRANK, G, LDG, JVEC, NPLUS, U, LDU, V, LDV, Q, LDU, TOL, IFLAGS, STATUS, TCPU, INFO)
  IF (INFO(1) .NE. 0) THEN
     PRINT *, INFO(2)
     STOP 'Error dumping output file!'
  END IF

  DEALLOCATE(V)
  DEALLOCATE(U)
  DEALLOCATE(Q)
  DEALLOCATE(JVEC)
  DEALLOCATE(G)

  CALL H5GCLOSE_F(GID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error closing the output group!'

  CALL H5FCLOSE_F(FID, INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error closing the output file!'

  CALL H5CLOSE_F(INFO(1))
  IF (INFO(1) .NE. 0) STOP 'Error shutting down HDF5!'

#ifndef NDEBUG
  STOP 'jk.exe successfully terminated.'
#endif

CONTAINS

  INCLUDE 'dmkldm.f90'
  INCLUDE 'invgjp.f90'

  SUBROUTINE READCL(AH5F, AH5G, AH5R, IFLAGS, INFO)
    IMPLICIT NONE

    INTEGER, PARAMETER :: ARGCNT = 4

    CHARACTER(LEN=ARGLEN), INTENT(OUT) :: AH5F, AH5G, AH5R
    INTEGER, INTENT(OUT) :: IFLAGS, INFO(2)

    CHARACTER(LEN=ARGLEN) :: ARGSTR
    INTEGER :: LENGTH

    INFO(1) = COMMAND_ARGUMENT_COUNT()
    IF ((INFO(1) .LT. 0) .OR. (INFO(1) .GT. ARGCNT)) STOP 'jk.exe H5F H5G H5R IFLAGS'

    IF (INFO(1) .GE. 1) THEN
       CALL GET_COMMAND_ARGUMENT(1, ARGSTR, LENGTH, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) = -1
          RETURN
       END IF
    ELSE
       PRINT *, 'H5F (input file):'
       READ *, ARGSTR
    END IF
    AH5F = TRIM(ARGSTR)

    IF (INFO(1) .GE. 2) THEN
       CALL GET_COMMAND_ARGUMENT(2, ARGSTR, LENGTH, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) = -2
          RETURN
       END IF
    ELSE
       PRINT *, 'H5G (input/output group):'
       READ *, ARGSTR
    END IF
    AH5G = TRIM(ARGSTR)

    IF (INFO(1) .GE. 3) THEN
       CALL GET_COMMAND_ARGUMENT(3, ARGSTR, LENGTH, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) = -3
          RETURN
       END IF
    ELSE
       PRINT *, 'H5R (output file):'
       READ *, ARGSTR
    END IF
    AH5R = TRIM(ARGSTR)

    IF (INFO(1) .GE. 4) THEN
       CALL GET_COMMAND_ARGUMENT(4, ARGSTR, LENGTH, INFO(2))
       IF (INFO(2) .NE. 0) THEN
          INFO(1) = -4
          RETURN
       END IF
    ELSE
       PRINT *, 'IFLAGS:'
       READ *, ARGSTR
    END IF
    READ (ARGSTR,*) IFLAGS

    INFO(2) = INFO(1) - ARGCNT
    INFO(1) = 0
  END SUBROUTINE READCL
END PROGRAM JK
