PURE LOGICAL FUNCTION LDOROT(F, G, H, TOL, HYP)
  IMPLICIT NONE

  DOUBLE PRECISION, INTENT(IN) :: F, G, H, TOL
  LOGICAL, INTENT(IN) :: HYP

  DOUBLE PRECISION :: GA

  GA = ABS(G)
  LDOROT = (F .NE. (F + GA)) .OR. (H .NE. (H + GA))
END FUNCTION LDOROT

SUBROUTINE JKSTEP(UPPER, I, J, M, N, G, LDG, U, LDU, V, LDV, JVEC, NPLUS, TOL, SWEEP, SWHALF, STEP, HYP, INFO)
  IMPLICIT NONE

  LOGICAL, INTENT(IN) :: UPPER
  INTEGER, INTENT(IN) :: I, J, M, N, LDG, LDU, LDV, JVEC(N), NPLUS, SWEEP, SWHALF
  DOUBLE PRECISION, INTENT(IN) :: TOL
  DOUBLE PRECISION, INTENT(INOUT) :: G(LDG,N), U(LDU,M), V(LDV,N)
  INTEGER, INTENT(INOUT) :: STEP
  LOGICAL, INTENT(OUT) :: HYP
  INTEGER, INTENT(OUT) :: INFO(2)

  DOUBLE PRECISION :: F0, G0, H0, CU, SU, CV, SV, F1, H1, PARAMU(5), PARAMV(5)
  LOGICAL :: RHSIDE
  INTEGER :: INSTAT

  EXTERNAL :: DROTM

  INFO = 0
  STEP = STEP + 1
  HYP = (JVEC(I) .NE. JVEC(J))

  F0 = G(I,I)
  H0 = G(J,J)

  IF (UPPER) THEN
     G0 = G(I,J)
  ELSE
     G0 = G(J,I)
  END IF

  IF (G0 .EQ. ZERO) RETURN

  IF (LDOROT(F0, G0, H0, TOL, HYP)) THEN
     INFO(2) = 1
     PARAMU(1) = MONE
     PARAMV(1) = MONE

     IF (HYP) THEN
        CALL DKOGH2(UPPER, F0, G0, H0, TOL, RHSIDE, CU, SU, CV, SV, F1, H1, INSTAT)
     ELSE
        CALL DKOGT2(UPPER, F0, G0, H0, TOL, RHSIDE, CU, SU, CV, SV, F1, H1, INSTAT)
     END IF

     PARAMU(2) =  CU
     PARAMU(3) = -SU
     PARAMU(4) =  SU
     PARAMU(5) =  CU

     IF (HYP) THEN
        PARAMV(2) =  CV
        PARAMV(3) = -SV
        PARAMV(4) = -SV
        PARAMV(5) =  CV
     ELSE
        PARAMV(2) =  CV
        PARAMV(3) = -SV
        PARAMV(4) =  SV
        PARAMV(5) =  CV
     END IF

     IF (RHSIDE) THEN
        CALL DROTM(M, G(1,I), 1,   G(1,J), 1,   PARAMV)
        CALL DROTM(N, G(I,1), LDG, G(J,1), LDG, PARAMU)
     ELSE
        CALL DROTM(N, G(I,1), LDG, G(J,1), LDG, PARAMU)
        CALL DROTM(M, G(1,I), 1,   G(1,J), 1,   PARAMV)
     END IF

     CALL DROTM(M, U(I,1), LDU, U(J,1), LDU, PARAMU)
     CALL DROTM(N, V(1,I), 1,   V(1,J), 1,   PARAMV)

     G(I,I) = F1
     G(J,J) = H1
  ELSE
     INFO(2) = -1
  END IF
  G(I,J) = ZERO
  G(J,I) = ZERO
END SUBROUTINE JKSTEP
