RM=del /F
AR=lib.exe
ARFLAGS=/NOLOGO /VERBOSE
!INCLUDE ..\..\..\libpvn\src\pvn.mk
FC=$(PVN_FC)
FFLAGS=$(PVN_FCFLAGS) /DUSE_INTEL /DUSE_X64 /DUSE_WINDOWS
LDFLAGS=$(PVN_LDFLAGS) /LIBPATH:. $(TYPE)jk.lib /LIBPATH:..\shared jk.lib $(PVN_LIBS)
